# Generated by Django 4.2.7 on 2024-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOGETHERING_APP', '0003_alter_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(),
        ),
    ]
