# Generated by Django 4.2.7 on 2024-01-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOGETHERING_APP', '0004_alter_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
