# Generated by Django 4.2.7 on 2024-01-21 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TOGETHERING_APP', '0007_remove_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
