# Generated by Django 4.2.7 on 2024-04-03 05:25

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TOGETHERING_APP', '0008_video_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
